version: '3'

services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    env_file: .env
    ports:
      - '${APP_PORT}:80'
    restart: unless-stopped
    links:
      - db
  db:
    image: mysql:8
    restart: unless-stopped
    ports: 
      - "3306"
    command: --default-authentication-plugin=mysql_native_password
    env_file: .env
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - ./dbdata:/var/lib/mysql
